# This workflow will deploy a yaml project

name: Java CD with Gradle

on: 
    pull_request: 
        types: [opened,synchronize,reopened]


run-name: Sonarqube vuln scan

jobs:
   sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Setup Code Checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      -
        name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

            
    
    

        
    





