# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Project Scan

on:
  push:
    branches: [ master, update-workflow ]
  pull_request:
    branches: [ master ]
    types: [opened,synchronize,reopened]

jobs:
  build:
    name: Setup Gradle
    runs-on: ubuntu-latest

    steps:
      - 
        name: Setup Code Checkout
        uses: actions/checkout@v2
        
      - 
        name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - 
        name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - 
        name: Build with Gradle
        run: ./gradlew build

      - 
        name: Show JAR output and path
        run: ls -la build/libs

      -
        name: Show JAR file path
        run: |
          pwd
          ls -R

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: percharch/only-one:latest

  test:
    name: Env Setup + sonarqube scan
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code for Sonarqube Scan
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - 
        name: Sonarqube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


