# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Project Scan

on:
  push:
    branches: [ master, update-workflow ]
  pull_request:
    branches: [ master ]
    types: [opened,synchronize,reopened]

jobs:
  build:
    name: Setup Gradle + Compiled Code
    runs-on: ubuntu-latest

    steps:
      - 
        name: Setup Code Checkout
        uses: actions/checkout@v2
        
      - 
        name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - 
        name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - 
        name: Build with Gradle
        run: ./gradlew build --scan

      - 
        name: Build Classes with Gradle
        run: ./gradlew classes

      - 
        name: Show JAR + Classes output and path
        run: |
          ls -la build/libs
          ls -la build/classes/java/main

      -
        name: Show JAR file path
        run: |
          pwd
          ls -R

  test:
    name: Sonarqube Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Checkout Code for Sonarqube Scan
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
          
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Print PATH
        run: echo $PATH

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Print PATH
        run: echo $PATH

      - 
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: build/libs
          build-contexts: 
            name=.
          push: true
          tags: percharch/only-one:App-Java-latest

